/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/control': RouteRecordInfo<'/control', '/control', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/evaluation/entry': RouteRecordInfo<'/evaluation/entry', '/evaluation/entry', Record<never, never>, Record<never, never>>,
    '/evaluation/sheets': RouteRecordInfo<'/evaluation/sheets', '/evaluation/sheets', Record<never, never>, Record<never, never>>,
    '/replication': RouteRecordInfo<'/replication', '/replication', Record<never, never>, Record<never, never>>,
    '/settings/parameters': RouteRecordInfo<'/settings/parameters', '/settings/parameters', Record<never, never>, Record<never, never>>,
    '/settings/schedule': RouteRecordInfo<'/settings/schedule', '/settings/schedule', Record<never, never>, Record<never, never>>,
    '/settings/teams': RouteRecordInfo<'/settings/teams', '/settings/teams', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/renderer/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/renderer/pages/control.vue': {
      routes: '/control'
      views: never
    }
    'src/renderer/pages/dashboard.vue': {
      routes: '/dashboard'
      views: never
    }
    'src/renderer/pages/evaluation/entry.vue': {
      routes: '/evaluation/entry'
      views: never
    }
    'src/renderer/pages/evaluation/sheets.vue': {
      routes: '/evaluation/sheets'
      views: never
    }
    'src/renderer/pages/replication.vue': {
      routes: '/replication'
      views: never
    }
    'src/renderer/pages/settings/parameters.vue': {
      routes: '/settings/parameters'
      views: never
    }
    'src/renderer/pages/settings/schedule.vue': {
      routes: '/settings/schedule'
      views: never
    }
    'src/renderer/pages/settings/teams.vue': {
      routes: '/settings/teams'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
