/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/tournament/[id]/control': RouteRecordInfo<'/tournament/[id]/control', '/tournament/:id/control', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/tournament/[id]/dashboard': RouteRecordInfo<'/tournament/[id]/dashboard', '/tournament/:id/dashboard', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/tournament/[id]/evaluation/entry': RouteRecordInfo<'/tournament/[id]/evaluation/entry', '/tournament/:id/evaluation/entry', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/tournament/[id]/evaluation/sheets': RouteRecordInfo<'/tournament/[id]/evaluation/sheets', '/tournament/:id/evaluation/sheets', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/tournament/[id]/replication': RouteRecordInfo<'/tournament/[id]/replication', '/tournament/:id/replication', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/tournament/[id]/settings/parameters': RouteRecordInfo<'/tournament/[id]/settings/parameters', '/tournament/:id/settings/parameters', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/tournament/[id]/settings/schedule': RouteRecordInfo<'/tournament/[id]/settings/schedule', '/tournament/:id/settings/schedule', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/tournament/[id]/settings/teams': RouteRecordInfo<'/tournament/[id]/settings/teams', '/tournament/:id/settings/teams', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/renderer/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/renderer/pages/tournament/[id]/control.vue': {
      routes: '/tournament/[id]/control'
      views: never
    }
    'src/renderer/pages/tournament/[id]/dashboard.vue': {
      routes: '/tournament/[id]/dashboard'
      views: never
    }
    'src/renderer/pages/tournament/[id]/evaluation/entry.vue': {
      routes: '/tournament/[id]/evaluation/entry'
      views: never
    }
    'src/renderer/pages/tournament/[id]/evaluation/sheets.vue': {
      routes: '/tournament/[id]/evaluation/sheets'
      views: never
    }
    'src/renderer/pages/tournament/[id]/replication.vue': {
      routes: '/tournament/[id]/replication'
      views: never
    }
    'src/renderer/pages/tournament/[id]/settings/parameters.vue': {
      routes: '/tournament/[id]/settings/parameters'
      views: never
    }
    'src/renderer/pages/tournament/[id]/settings/schedule.vue': {
      routes: '/tournament/[id]/settings/schedule'
      views: never
    }
    'src/renderer/pages/tournament/[id]/settings/teams.vue': {
      routes: '/tournament/[id]/settings/teams'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
